name: Build Tensor-VoLTE-VoWifi Canary Module

on:
  push:
    branches:
      - canary
    workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Build module
        run: |
          chmod +x sh.sh
          bash sh.sh

      - name: Get commit hash
        id: commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tensor-VoLTE-VoWifi-Canary-${{ steps.commit.outputs.sha }}
          path: Tensor-VoLTE-VoWifi-Canary-*.zip